### ISSUE TITLE
Do we have proper example of auth-connect with identity-vault with vue

### ISSUE THREAD

**Issue by rajuketech** [ionic-enterprise/tea-taster-vue#1]
We are facing a issue in android device we are using a auth connect with AWS Cognito with vault, secure store is not working properly, looking a proper example in doc, not finding

Not able to find a feature/auth-connect branch, as mentioned in readme

@kensodemann Can you please help on it?

**Comment by rajuketech** [comment]
@kensodemann Can you please help on it?

**Comment by kensodemann** [comment]
You can view the old version of this project here: https://github.com/kensodemann/tea-taster-vue. It has a branch that uses both AC and IV.

You can also see this app: https://github.com/ionic-enterprise/auth-playground-vue

Your purchase of AC and IV, however, also give you access to our ticketing system for support: https://ionic.zendesk.com/hc/en-us

For specific issues you may be having, you are best off asking your question there. If you have not purchased yet, then you are best off contacting the sales representative you are working with.
